-- ============================================================
-- migration_grupos.sql
-- Ejecutar una sola vez en SQL Server para agregar grupos
-- ===========================================================deb